### ISSUE TITLE
VenusGX

### ISSUE THREAD

**Issue by D4gu8** [ricott/homey-com.victronenergy#1]
Hi, I noticed a newly added Victron to the home. Unfortunately, it does not work on the older VenusGX. VenusGX uses the same OS as the new CerboGX, but adding it to home ends in error. "Cannot read property 'vrmId' of undefined" Do I need root privileges or does it not work on all VenusOS devices? Thanks for the reply D.

**Comment by ricott** [comment]
Hi!

Did you manage to find your way to the forum page and read the instructions there? 
Athom doesn't make it super easy to direct people there; https://community.athom.com/t/app-victron-energy/46219

There is a section at the top, on what you need to do when adding a GX device to your Homey.
I guess the error you mention you get when you try to add the device? Will fix that as well so it simply says it cant find the device.
