### ISSUE TITLE
Enhancement - Grid cumulative  

### ISSUE THREAD

**Issue by Busta999** [ricott/homey-com.victronenergy#10]
Thanks for the Victron App extremely useful - much appreciated.

I am looking for a way to use the Victron App with Power By The Hour to track actual Electric consumption and Costs.

Is there anyway to get out of the Victron App how many kWh have actually gone through the Grid in any one day period?

Something that resets daily at local midnight. Then builds through the day.

It would be extremely useful and save me from getting daily meter readings form energy supplier and adding to a spreadsheet manually every morning.

If I can then add in the elec for the hot water (Sonoff PWR3) energy used to charge the car from the Zappi App and I will have all the logging automated :-)

**Comment by ricott** [comment]
Adding lifetime grid import and export in v1.1.1
