### ISSUE TITLE
How to use the WHEN...."SoC changed to [[soc]]"?

### ISSUE THREAD

**Issue by tmsluijter** [ricott/homey-com.victronenergy#12]
I like to switch off heavy consumers when my battery SOC becomes low. I tried to start the flow with the When..."SoC changed to [[soc]]" but can't specify the minimum SOC %. Can you please explain when I can set the minimum allowable SOC% that will trigger the flow that switches off my heavy loads?

**Comment by ricott** [comment]
I realize it is confusing, it was coded to only be a trigger without a filter - but not displayed like it now.
You can use the trigger you have selected and then add a logic card as a condition to use the soc passed from the trigger. Something like this.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/31240726/214950309-c0ebeed0-9dcf-4b95-96c5-ab3962f43c81.png">

Please note that the action will be triggered multiple times, one time for each change of SoC that is below your threashold.

**Comment by tmsluijter** [comment]
Thanks Richard for the quick and clear reply👍Sent from my iPhoneOn 26 Jan 2023, at 23:06, Richard Barkestam ***@***.***> wrote:﻿
I realize it is confusing, it was coded to only be a trigger without a filter - but not displayed like it now.
You can use the trigger you have selected and then add a logic card as a condition to use the soc passed from the trigger. Something like this.

Please note that the action will be triggered multiple times, one time for each change of SoC that is below your threashold.

**Comment by tmsluijter** [comment]
Dear Richard,

See attached flow. Even-though the actual SOC is around 98% and action is only required under the 50% it keeps toggling the Aircons on and off every second for a bout 3 times, then noting and 10 minutes later the same. Any idea what is going on here? 

![Screenshot 2023-01-29 at 16 15 44](https://user-images.githubusercontent.com/116089168/215332951-586a2b8b-8c17-4b42-be5b-8523921f7d92.png)

**Comment by ricott** [comment]
Sounds strange, unless we would see something in Homey Insights for the SoC value. Can you have a look there and see if it changes? I would still use the SoC token value from the trigger in a logic card - to make sure the triggered value is what is used in the flow. You can also add to the push notification the value of the SoC token, then you will see what value the Homey app thinks it has.

**Comment by tmsluijter** [comment]
As you suggested I created the push notifications including the actual values received for SOC and noticed that the SOC in the flow regularly drops instantly from 98% to 0% and back to 98% again. I suspect this has to do with the Modbus registers being refreshed by Victron while Homey is reading the values. 
It seems to work fine after I added a 2 second delay after the SOC is detected and before the values are tested for "below". Fingers crossed it will keep working now.

**Comment by tmsluijter** [comment]
One more attempt to make it work: I added a 2 second delay after the SOC changed trigger and then test the SOC at the same time for 3 different values. Fingers crossed this workaround will fix the Modbus read issue for me. I'm more than happy to perform some more tests for your developers on my system.
![Screenshot 2023-02-04 at 15 27 11](https://user-images.githubusercontent.com/116089168/216770404-bba4052a-16fe-49ff-8516-2cdd18f13ceb.png)
