### ISSUE TITLE
Victron energy app cannot install

### ISSUE THREAD

**Issue by Sjoerd1987** [ricott/homey-com.victronenergy#14]
Hello, i received my homey pro today, and i want to install victron energy to connect my cerbo gx to my homey.
But in the homey app i get the message that the homey is not compatible.

**Comment by Sjoerd1987** [comment]
Hello,
Yes i’m sure it is the homey pro early 2023
![IMG_6468](https://user-images.githubusercontent.com/132299130/235608933-4c2c4cbe-fc6b-40f7-9d36-fa4d836db3f4.png)

**Comment by ricott** [comment]
Given that you have a cloud region I would assume it is the Bridge and not the Pro Homey you have got.
The settings for my Homey Pro 2023 look like the image below. Further, I think you have to have the beta version of the mobile app (version 7.x) to use the Homey Pro 2023.

![image](https://user-images.githubusercontent.com/31240726/235611766-933bd576-1e01-4592-af3b-e93df9eb134f.png)

**Comment by Sjoerd1987** [comment]
ok thanks for the info, i'll have a look tonight to see where the problem is
