### ISSUE TITLE
At new 1.1.6 release SOC no more visible

### ISSUE THREAD

**Issue by tmsluijter** [ricott/homey-com.victronenergy#15]
What happened to the SOC in % in the GX device status screen? It is no longer shown in the device details. 
![Uploading IMG_4712.png…]()

**Comment by ricott** [comment]
After a brief conversation in the forum thread the SoC was migrated to a built in battery capability in Homey.

<img width="415" alt="image" src="https://github.com/ricott/homey-com.victronenergy/assets/31240726/9fb10dc7-f1a1-4df4-8266-062fc048bd3c">

<img width="128" alt="image" src="https://github.com/ricott/homey-com.victronenergy/assets/31240726/3262d2a9-86c8-469c-a4bd-3ceae8cd559b">
