### ISSUE TITLE
Please add temperature sensors

### ISSUE THREAD

**Issue by parostberg** [ricott/homey-com.victronenergy#19]
Is it possible to add Ruuvi temperature sensors that are connected to the Cerbo GX?
![Ruuvi](https://github.com/ricott/homey-com.victronenergy/assets/24352332/4a0b52d8-68a9-4d8a-9521-1ff813f19ee3)

**Comment by ricott** [comment]
Have a look at the new [test version](https://homey.app/a/com.victronenergy/test/).
I don't have a temp sensor myself, so expect some problems ...

**Comment by parostberg** [comment]
I have the Cerbo GC on a different location. Is it possible to reach the temperature sensor from the "Victron VRM" device?or do I need co connect locally?
![image](https://github.com/ricott/homey-com.victronenergy/assets/24352332/b4098bd3-86ce-4590-9e7c-294e77980953)

**Comment by ricott** [comment]
@parostberg You need to connect via local LAN. The app connects to the GX device using Modbus. If connecting to a remote Cerbo you need a type of VPN connectivity between the sites, then it would work of course.
