### ISSUE TITLE
Condition IF

### ISSUE THREAD

**Issue by D4gu8** [ricott/homey-com.victronenergy#2]
Hi, first of all thank you for this plugin. Could you please add the IF AC Loads condition in the next update? Because when I do the load condition, I am not so much interested in the consumption, I am more interested in the inverter output load. I haven't figured out how else to do it in the IF condition and the consumption is dependent on efficiency, voltage, temperature and thus not very accurate. I'd rather need to track the AC Loads as it is in the VRM graph. Thanks for understanding DJ.

**Comment by ricott** [comment]
Hi!

I'm not sure which field you want added as a condition. There are a lot of fields that are possible to query, so need to know which one(s) exactly. When I know which one adding a condition is not a problem.

When checking I suspect it could be modbus registries 817 to 819.
/Ac/Consumption/L1/Power
/Ac/Consumption/L2/Power
/Ac/Consumption/L3/Power

They have this comment in the excel I'm looking at "Power supplied by system to loads." You are looking for a summary across all three phases to use a condition on?

**Comment by D4gu8** [comment]
Hi,

The modbus register is the ac side of the input. I would like to field the
ac output. Currently it can be tracked as consumption, but as I wrote, it
is better to track the output load in VA or WATTs. I don't know if this is
an option. I have only 1 phase offgrid setup.

Thanks for the response DJ.




Dne ne 22. srp 2021 20:40 uživatel ricott ***@***.***> napsal:

**Comment by ricott** [comment]
Think I have the correct modbus registries. I'll release a test version and you can give it a go.

**Comment by ricott** [comment]
https://homey.app/a/com.victronenergy/test/

**Comment by D4gu8** [comment]
Hi, I don't think we understand each other. Modbus is mostly like an input
meter. I'd like output power. In VRM is:

AC Input -Multiplus2 - AC Loads
and Aku + Regl.

I would like to use AC Loads in the condition in the variable Watts, or VA.
Thank you for the beta. However, I have found that you can use AC Loads in
the AND condition. So can it be done as every 5s and AC Loads over, do the
action. But easier would be AC Loads more than- then do the action
(unplugging the washing machine).
Thanks for the responses DJ.

Dne po 23. srp 2021 9:42 uživatel ricott ***@***.***> napsal:

**Comment by D4gu8** [comment]
Now I was thinking that I can write the condition as, if the grid power is less than 10W and the AC Loads is less than 2000W do the action and so that's enough for me as it is in this beta. I don't even know if it was already like that in the original stable version, because I was looking for it in the first condition.

**Comment by ricott** [comment]
AC loads that we talked about initially is what I added. It matches what VRM calls AC loads.
![image](https://user-images.githubusercontent.com/31240726/130511144-486df01e-7e47-4dbd-aaa7-3cd435a00941.png)

`Consumption` that is available in the app from the beginning is `pv power - battery power + grid power`.
You can invert any condition, below being default but you can invert that to become above.

**Comment by ricott** [comment]
New test version today, added also conditions for AC inputs and outputs, you can have a look at them as well.

**Comment by D4gu8** [comment]
I tried it today and it works perfectly. Thanks a lot for your help.
