### ISSUE TITLE
Error reading data

### ISSUE THREAD

**Issue by chrisboer** [ricott/homey-com.victronenergy#20]
CERBO GX

2023-12-08 16:34:11
Error: Failed to read 'System; maximum cell voltage' (1291) using unitId '100' (battery)
    at modbusReading (/app/lib/victron.js:486:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 38)

![image](https://github.com/ricott/homey-com.victronenergy/assets/23163409/1e694189-e058-4e5c-8e28-68df68e3e53f)

![image](https://github.com/ricott/homey-com.victronenergy/assets/23163409/9667c21d-9049-4126-ac23-7cc02654d2c2)

**Comment by ricott** [comment]
Unit id `100` is supposed to be reserved for `com.victronenergy.system`.
However, I have seen that multiple services share the same unit id, so it is not unique to your case.
Currently, the Modbus package I use seems to dislike opening multiple connections using the same Modbus unit id. 
I'll see if I can work around that somehow.
For the time being, you can set the battery to unit id -1 to get rid of the error.

**Comment by ricott** [comment]
Please try out the new [test version](https://homey.app/a/com.victronenergy/test/)
