### ISSUE TITLE
Tank levels

### ISSUE THREAD

**Issue by rickardkk** [ricott/homey-com.victronenergy#21]
Would it be possible to have tank level readings?
Not only would that help with resistive sensors but we can also use the Cerbo as a bridge to Homey for the Mopeka BT ultra sonic sensors.

**Comment by ricott** [comment]
Don't have a tank myself. Would that be `com.victronenergy.tank`?
As per the modbus spec it looks like you can only have one tank?

<img width="2015" alt="image" src="https://github.com/ricott/homey-com.victronenergy/assets/31240726/91609ee8-ecc8-4555-b181-d6668758d401">

**Comment by rickardkk** [comment]
Great that you’re looking into this one.
Yes, com.victronenergy.tank is correct and you are also right about multiple tanks (they get it’s own unit id).

**Comment by ricott** [comment]
Have a look at the new [test version](https://homey.app/a/com.victronenergy/test/).
I don't have a tank myself, so expect some problems ...

**Comment by rickardkk** [comment]
Great! But unfortunately it crashes on startup.
Can I help buy sending logs? (If possible)



- - -
Bästa hälsningar / Best regards
Rickard Källqwist

earselect.se
Hamngatan 26B
SE-185 32 VAXHOLM

+46(0)70 00 888 00
***@***.***
www.earselect.se


fre 29 dec. 2023 kl. 17:44 skrev Richard Barkestam ***@***.***

**Comment by ricott** [comment]
What crashed? When you added a tank device? Did you get an error?

The device itself has a setting which shows last modbus error. You can also trigger a manual diagnostic report on the app settings.

**Comment by rickardkk** [comment]
Unfortunately the app never starts. It says “App unavailable” and “Crashed”
in Homey.
Tried to trigger a manual diagnostic report on the app settings but that
doesn’t work.

Also the Advanced settings is missing.

- - -
Bästa hälsningar / Best regards
Rickard Källqwist

earselect.se
Hamngatan 26B
SE-185 32 VAXHOLM

+46(0)70 00 888 00
***@***.***
www.earselect.se


fre 29 dec. 2023 kl. 22:53 skrev Richard Barkestam ***@***.***

**Comment by rickardkk** [comment]
Managed to complete a diagnostic rapport:
ac21d4f1-34f7-4e81-a390-e3b10a758de4




- - -
Bästa hälsningar / Best regards
Rickard Källqwist

earselect.se
Hamngatan 26B
SE-185 32 VAXHOLM

+46(0)70 00 888 00
***@***.***
www.earselect.se


fre 29 dec. 2023 kl. 22:57 skrev Rickard Källqwist ***@***.***>:

**Comment by ricott** [comment]
I got the diag report, trying to understand it ...
As usual, things work fine here :(

Do you have a lot of flows connected to your GX device, or is it possible to remove and re-add it?

**Comment by rickardkk** [comment]
No problem. I’ll try to remove and re-add.



- - -
Bästa hälsningar / Best regards
Rickard Källqwist

earselect.se
Hamngatan 26B
SE-185 32 VAXHOLM

+46(0)70 00 888 00
***@***.***
www.earselect.se


fre 29 dec. 2023 kl. 23:13 skrev Richard Barkestam ***@***.***

**Comment by rickardkk** [comment]
Unfortunately the problem remains even when starting fresh. DR:
a3a976d9-0406-465b-9068-27096dec984a




- - -
Bästa hälsningar / Best regards
Rickard Källqwist

earselect.se
Hamngatan 26B
SE-185 32 VAXHOLM

+46(0)70 00 888 00
***@***.***
www.earselect.se


fre 29 dec. 2023 kl. 23:15 skrev Rickard Källqwist ***@***.***>:

**Comment by ricott** [comment]
I reverted a change I did involving the old GX device. There is a new test version.
The tank and temp sensors use the same new code though for reading the modbus registries. Interesting to see if that works ...

**Comment by rickardkk** [comment]
Great!

Now the GX is working again but I get “Couldn’t connect to host” when
trying to add a tank or temp sensor. I’m not sure if that’s because of the
setup with  BT tank sensors but I can try a traditional within a couple of
days when I get home (on holiday right now).

Super excited about this one as it will open up a way to automate the water
maker in a better way (living off grid).





- - -
Bästa hälsningar / Best regards
Rickard Källqwist

earselect.se
Hamngatan 26B
SE-185 32 VAXHOLM

+46(0)70 00 888 00
***@***.***
www.earselect.se


fre 29 dec. 2023 kl. 23:27 skrev Richard Barkestam ***@***.***

**Comment by ricott** [comment]
> I get “Couldn’t connect to host” when trying to add a tank or temp sensor

It validates using the Modbus `Product ID` property. If it can read that, I assume we have the correct device type.
Check the Unit ID of the tank/temp sensor as usual and use that one. Same IP and port as for your GX device.
`com.victronenergy.tank` and `com.victronenergy.temperature`

Lets continue once you are back home 👍

**Comment by rickardkk** [comment]
Thanks!!
I’ll get back to you as soon as I’m home again 👍🏻



- - -
Bästa hälsningar / Best regards
Rickard Källqwist

earselect.se
Hamngatan 26B
SE-185 32 VAXHOLM

+46(0)70 00 888 00
***@***.***
www.earselect.se


lör 30 dec. 2023 kl. 16:45 skrev Richard Barkestam ***@***.***

**Comment by rickardkk** [comment]
Hi again,

I’m back at the island and can happily report that my tanks and temperature
readings are working properly. Great work and a much appreciated feature
upgrade to the already great Victron integration with Homey👍🏻



- - -
Bästa hälsningar / Best regards
Rickard Källqwist

earselect.se
Hamngatan 26B
SE-185 32 VAXHOLM

+46(0)70 00 888 00
***@***.***
www.earselect.se


lör 30 dec. 2023 kl. 16:47 skrev Rickard Källqwist ***@***.***>:

**Comment by ricott** [comment]
Great! Thanks for testing!
