### ISSUE TITLE
New setup with DVCC problem

### ISSUE THREAD

**Issue by D4gu8** [ricott/homey-com.victronenergy#3]
Hi, I'm calling again with a problem. I noticed that after connecting BMS to VenusGX, the rules stopped working. It was probably caused by adding a usb/ttl converter and a different battery ID. I currently have ID 1 for BMS and 245 for smartshunt, but neither is in the selection when adding venus gx to homey. Can't you change the selection box to a value box so I can change it? Thank you in advance for your willingness DJ.

**Comment by D4gu8** [comment]
![Screenshot_20211108_214120_com android chrome](https://user-images.githubusercontent.com/82838336/140816668-97489de4-ebc3-4570-bf1a-4d23130c82ef.jpg)

**Comment by D4gu8** [comment]
![Uploading Screenshot_20211108_214114_com.android.chrome.jpg…]()

**Comment by D4gu8** [comment]
![Uploading Screenshot_20211108_214100_app.homey.jpg…]()

**Comment by D4gu8** [comment]
![Screenshot_20211108_214114_com android chrome](https://user-images.githubusercontent.com/82838336/140816833-8ce4894c-aec6-49f0-b82e-c56404182c40.jpg)

**Comment by D4gu8** [comment]
![Screenshot_20211108_214100_app homey](https://user-images.githubusercontent.com/82838336/140816869-50748fd9-b7cd-41e7-9bff-13871772865a.jpg)

**Comment by ricott** [comment]
I'll switch it to input fields 👍

**Comment by D4gu8** [comment]
Great, and when is the modified version coming out please?

**Comment by ricott** [comment]
https://homey.app/a/com.victronenergy/test/

**Comment by D4gu8** [comment]
Thanks I tested adding it but it ends up with a value error in the vebus string. I am attaching screenshots.
![Screenshot_20211110_225537_app homey](https://user-images.githubusercontent.com/82838336/141200022-56078df7-1a11-4439-a211-21c763450479.jpg)
![Screenshot_20211110_225503_app homey](https://user-images.githubusercontent.com/82838336/141200044-8f60b394-f5a2-4312-8d54-dc71bf24f9b4.jpg)

**Comment by ricott** [comment]
When do you get the error, after clicking next to add the device?
And you didn't add any space or non-numeric values in the field? (This is the problem with an open input field)

Was the device added even with the error? If so, what values do you see for vebus and battery id in advanced settings? Maybe good that you try to add the device from scratch, so we capture potential problems there - but these fields are possible to also edit for existing devices.

**Comment by D4gu8** [comment]
Hi,
The error pops up when you click next and victron is not added. I have entered purely the number 242 for vebus and 1 for battery. I even tried manually deleting the field. I am attaching a screenshot of the input. So I am thinking to make a 1-255 rollup and select from that and calmly redefine something as default?
![Screenshot_20211110_233127_app homey](https://user-images.githubusercontent.com/82838336/141204619-c542586c-6b32-4b5e-a32e-86fc3107f61f.jpg)

**Comment by ricott** [comment]
Think I found the problem. There is a new testversion.
The validation is actually pretty good in the add new device flow (not in edit). So it will now let you move on if it can't validate the provided id's - they have to be accurate.

**Comment by D4gu8** [comment]
Beautiful. It's already working. Thanks and just one last question. There are items in settings and advanced settings and dvcc is reported as disabled. Do you have bi-directional communication with any particular BMS reading and setting? I'm currently using DVCC through a BMS, but this doesn't affect it. It's the dbus-serialbattery project on github for VenusGX. It's a universal DVCC and CCCV communication for BMS like Dali, LLT, JTD. So just in case you feel like implementing it. 
Otherwise, thank you very much for the modification and everything seems to work. Thanks DJ.
