### ISSUE TITLE
Ergänzung AC-ignored und Relais 1/2 State

### ISSUE THREAD

**Issue by Dionysos1977** [ricott/homey-com.victronenergy#4]
Hallo Herr Barkestam,

Leider kann ich nicht programmieren. Ich würde mich aber freuen, wenn Sie sich die Mühe machen würden, die Steuerung für AC-ignored und den beiden Relais 1/2 hinzuzufügen.

Mit freundlichen Grüßen 

M. Donath

**Comment by ricott** [comment]
Hi!

My German is rusty, but Google translate gives me this
> the control for AC-ignored and the two relays 1/2

For relays, these are the ones you mean - on the GX device?

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/31240726/158678652-90f1ca6c-2468-461a-8512-6b5564f6069a.png">

For AC ignored I only find these, and they are not writeable - ie can't change the value.

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/31240726/158679346-5adcda06-1928-427e-b34f-7db6e6f58da2.png">

**Comment by ricott** [comment]
There is a new test version with support for controlling GX relay 1 and 2.

**Comment by Dionysos1977** [comment]
Hi there, said and done. :-) Many thanks for the quick implementation. I tested. works very well. I'm also happy to donate something to them if it's convenient. Sincerely yours M Donath
