### ISSUE TITLE
Victron Energy App Crashes

### ISSUE THREAD

**Issue by ianbednar** [ricott/homey-com.victronenergy#8]
Hi. I have installed and use your app. When it works, it is an fantastic app. However, it keeps crashing several times a day. I have logged the app until it crashes, and have noticed that it suddely uses a lot of memory and the CPU usage goes up a lot. I have seen it jump from about 14MB memory to 90 MB memory after a crash. The CPU whent up from 0% to 30%. Today i restarted the app after a crash. It then whent down from 140 MB memory to 14.4 MB memory and the cpu whent down from 10.4% to 0%. Sometimes the crash is so bad, that I have to restart Homey. My system freememeory goes from about 16% to 1% after the Victron app crashes. I also get a high loadavg, going from 0.7 to above 2. Have you experienced this before?

**Comment by ricott** [comment]
Hi!
Sorry for a very slow response ...
How have things worked out for you?

The things you describe above are nothing I have observed. I use the Homey app to control the charge current based on SoC - so I'm really dependent on it. I have my Cerbo connected via cable, then Homey obviously is connected via wifi. Do you have good connectivity between your GX device and Homey?
