### ISSUE TITLE
Generator control/state

### ISSUE THREAD

**Issue by Lmhog** [ricott/homey-com.victronenergy#9]
Hello, have just installed homey and the Victronenergy app. Works really fine. My system is off-grid, with solar panels, battery, and generator for backup power.
Is't possible to get generator into the app, maybe instead of grid, or as an option?
Thank you for a wonderful app.

**Comment by ricott** [comment]
Hi!
I added generator power and the active input source to the app.
Unfortunately, you must remove the GX device and add it again to see the new capabilities.
It is available as a [test version](https://homey.app/a/com.victronenergy/test/).

**Comment by Lmhog** [comment]
Hi
Back in my Cabine again. 
Remowed Cerbo, uppguraded app to test Version. 

Everything seems fine. Automatic correct input source was realey smooth. 
Thank you for a realy nice app.
